# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6e9d11fa3a494e77318abaa07ad743ad2d3af3e71b1d8715877b620898adbd9a078cdf1bb73510ead8a78cb018f07aefe430328d5f7480dd2f01160fc67bce5

test:
  secret_key_base: 93a49baf0725c717762598c7fdca59f676046814d4caa32fef50b3016662c291229bf631f2d08591b452e7b94824b1dd524fa3920284dafdab3bc4a8adc7c36b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d6e9d11fa3a494e77318abaa07ad743ad2d3af3e71b1d8715877b620898adbd9a078cdf1bb73510ead8a78cb018f07aefe430328d5f7480dd2f01160fc67bce5
